/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: defb37a9-102b-470c-8442-c3396eccd211

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the points of the trapezoid in the complex plane and prove the two required geometric identities using algebraic simplification of the distances.
The points are defined as follows:
- C is the origin (0,0).
- B is at (a,0).
- D is at (0,a).
- A is at (x,a).
- E is at (0, a-x).
- F is the projection of E onto AB.
- G is the intersection of AE and BD.
- H is the intersection of EF and BD.

We prove:
1. BF * HE = GE * BH (`polygon_ratio_1`)
2. BE * DH = BD * EH (`polygon_ratio_2`)
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of points A, B, C, D, E, F, G, H in the complex plane for the trapezoid problem.
-/
open Complex

noncomputable def pC : ℂ := 0
noncomputable def pD (a : ℝ) : ℂ := I * a
noncomputable def pB (a : ℝ) : ℂ := a
noncomputable def pA (a x : ℝ) : ℂ := x + I * a
noncomputable def pE (a x : ℝ) : ℂ := I * (a - x)

noncomputable def pF (a x : ℝ) : ℂ :=
  let AB := pA a x - pB a
  let EB := pE a x - pB a
  let t := (EB * star AB).re / (AB * star AB).re
  pB a + t * AB

noncomputable def pG (a x : ℝ) : ℂ := (x / 2) + I * (a - x / 2)

noncomputable def pH (a x : ℝ) : ℂ :=
  let den := 2 * a - x
  (a * x / den) + I * (2 * a * (a - x) / den)

/-
Prove that BF * HE = GE * BH in the configured trapezoid.
-/
open Complex Metric

theorem polygon_ratio_1 (a x : ℝ) (ha : a ≠ 0) (hx : x ≠ 0) (hden : 2 * a ≠ x) :
  dist (pF a x) (pB a) * dist (pE a x) (pH a x) = dist (pG a x) (pE a x) * dist (pH a x) (pB a) := by
  unfold pF pE pG pH at *;
  unfold pA pB at *;
  norm_num [ Complex.dist_eq, Complex.normSq, Complex.norm_def ];
  norm_num [ Complex.normSq, Complex.div_re, Complex.div_im ] at *;
  field_simp;
  rw [ ← Real.sqrt_mul <| by positivity, ← Real.sqrt_mul <| by positivity ];
  rw [ ← Real.sqrt_mul <| by positivity, ← Real.sqrt_mul <| by positivity ] ; ring;
  grind

/-
Prove that BE * DH = BD * EH in the configured trapezoid.
-/
open Complex Metric

theorem polygon_ratio_2 (a x : ℝ) (ha : a ≠ 0) (hx : x ≠ 0) (hden : 2 * a ≠ x) :
  dist (pE a x) (pB a) * dist (pD a) (pH a x) = dist (pD a) (pB a) * dist (pE a x) (pH a x) := by
  unfold pB pD pE pH;
  norm_num [ Complex.normSq, Complex.norm_def, Complex.dist_eq ];
  norm_cast; norm_num [ Complex.normSq, Complex.div_re, Complex.div_im, ha, hx, hden ] ; ring;
  rw [ ← Real.sqrt_mul, ← Real.sqrt_mul ];
  · grind;
  · positivity;
  · nlinarith [ sq_nonneg ( a - x ) ]